language: php

php:
  - 5.4

env:
  global:
    - secure: "W1jZcata0Foo3Sb5o7+Wlaf45SDoJLLFzxCqCgOL7ddv8POeWjQufebvAyl8d7fRKLRPWVdaYL2zONPfn57au6QyR1aCeypLAHpE52UyK5+dVHRbPvPnENIATb9UPjiWTSO4FCcGZmt7ixPZgJsWZirWPCnADcx5nHkgpgnrYT8="
    - secure: "ib/Xx3JBvx7xvMMBLqPq5jIErgBEQHix3tQk9l/7NCVtJ5gRkFhsGzHzSSzX41bHCQVSIIyZTePElsaqHJplTuuDO804UGFQMXEtzB/5kasyPOIsgfM15NWMN4rJb+wu/dsQPHJ7IbQafY8zICHqNbbvX6TGrSZ2EGxw/+B+3J0="

mysql:
  database: drupal
  username: root
  encoding: utf8

install:

  # Create MySQL Database
  - mysql -e 'create database drupal;'
  - sudo apt-get --quiet=2 install apache2 libapache2-mod-php5 php5-cli php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install Drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash

  # Prepare ./tests/behat/behat.local.yml
  - ./scripts/behat_local_yml.sh

  # Run composer
  - cd ./tests/behat
  - composer install

  # Going back
  - cd ../../

before_script:

  # Install Kickstart Profile
  - drush make --prepare-install build-commerce-kickstart.make kickstart --yes
  - cd kickstart
  - sudo chmod -R 777 sites/all/
  - sudo chmod -R 777 sites/default/files/
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php  si commerce_kickstart --sites-subdir=default --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce Kickstart Profile" --yes
  - drush cc all --yes
  - cd ../

  # Start the web server
  - ./scripts/apache_server.sh
  - sleep 5s

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5s

  # Get Selenium
  #- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
  #- java -jar selenium-server-standalone-2.39.0.jar > /dev/null 2>&1 &
  #- sleep 5

  - cd tests/behat

script:


  # Set env variable for behat params.
  - export BEHAT_PARAMS="extensions[Behat\MinkExtension\Extension][selenium2][wd_host]=$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub"

  # Setup sauce tunnel in the background and give it time to launch.
  - java -jar vendor/sauce/connect/lib/Sauce-Connect.jar -P 4445 $SAUCE_USERNAME $SAUCE_ACCESS_KEY > /dev/null 2>&1 &
  - sleep 45

  # Run behat tests
  #- ./bin/behat --no-paths
  - ./bin/behat -p Firefox-19 --no-paths

  # Shut down the sauce tunnel
  - kill $(ps aux | grep "Sauce-Connect" | grep -v 'grep' | awk '{print $2}')
  - cd ../../
